name: actions_build

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 1.21
      - name: Maven Package
        run: mvn -B clean package -DskipTests